### ISSUE TITLE
decompile exception in dnspy

### ISSUE THREAD

**Issue by fl380** [cawk/ConfuserEx-Unpacker-2#8]
This original code 
```C#
private int _JsyVKTz4egDrDK4nIzziWABIPAe
        {
            [MethodImpl(MethodImplOptions.NoInlining)]
            get
            {
                return this._OQoQ9XbznT8Iu2jioNCdczfKRBJ;
            }
            set
            {
                this._OQoQ9XbznT8Iu2jioNCdczfKRBJ = value;
                if (value != 0)
                {
                    goto IL_0A;
                }
                goto IL_46;
                uint num2;
                for (;;)
                {
                    IL_0F:
                    uint num;
                    switch ((num = (num2 ^ 3260840564u)) % 4u)
                    {
                    case 1u:
                        goto IL_46;
                    case 2u:
                        this._oJc2BO4chDQspZoCglkkMWePw6t = true;
                        num2 = (num * 323454812u ^ 606853161u);
                        continue;
                    case 3u:
                        goto IL_0A;
                    }
                    break;
                }
                return;
                IL_0A:
                num2 = 2178355814u;
                goto IL_0F;
                IL_46:
                _GmpWUy9gO61zI05x0MXZNizw70H._eLj8CcRwejFgttAmUN2D8hAeM5j hoaAztexvpJa1m22Oavu2vqnegc = this._HOaAztexvpJa1m22Oavu2vqnegc;
                if (hoaAztexvpJa1m22Oavu2vqnegc == null)
                {
                    return;
                }
                hoaAztexvpJa1m22Oavu2vqnegc(value);
                num2 = 3259521724u;
                goto IL_0F;
            }
        }
```
and in IL
```C#
.method private hidebysig 
		instance void _jpXhRjjjc80FUFutwWTZWcZsPyc (
			object '',
			class [mscorlib]System.EventArgs ''
		) cil managed 
	{
		// Header Size: 12 bytes
		// Code Size: 115 (0x73) bytes
		// LocalVarSig Token: 0x1100000B RID: 11
		.maxstack 3
		.locals init (
			[0] int32,
			[1] uint32
		)

		/* 0x0047B8D4 03           */ IL_0000: ldarg.1
		/* 0x0047B8D5 746F000001   */ IL_0001: castclass [System.Windows.Forms]System.Windows.Forms.TextBox
		/* 0x0047B8DA 284FD50106   */ IL_0006: call      string _omuaGIHkpB8HgJH84kunzdF5Q8b._GmpWUy9gO61zI05x0MXZNizw70H::'⁬‫‍‎‏⁯‍⁭‏‏‫⁮‪‭⁬​‏⁪⁪⁬⁬​⁮‭‍‫‭​⁭‍⁯⁫⁮‮​⁯⁫⁭⁪⁪‮$PST0601D54F'(class [System.Windows.Forms]System.Windows.Forms.Control)
		/* 0x0047B8DF 1200         */ IL_000B: ldloca.s  V_0
		/* 0x0047B8E1 282C03000A   */ IL_000D: call      bool [mscorlib]System.Int32::TryParse(string, int32&)
		/* 0x0047B8E6 2C5E         */ IL_0012: brfalse.s IL_0072

		/* 0x0047B8E8 20B805DE40   */ IL_0014: ldc.i4    1088292280
		// loop start (head: IL_0019)
			/* 0x0047B8ED 208587CC62   */ IL_0019: ldc.i4    1657571205
			/* 0x0047B8F2 61           */ IL_001E: xor
			/* 0x0047B8F3 25           */ IL_001F: dup
			/* 0x0047B8F4 0B           */ IL_0020: stloc.1
			/* 0x0047B8F5 1A           */ IL_0021: ldc.i4.4
			/* 0x0047B8F6 5E           */ IL_0022: rem.un
			/* 0x0047B8F7 45040000003A0000000200000024000000DCFFFFFF */ IL_0023: switch    (IL_0072, IL_003A, IL_005C, IL_0014)

			/* 0x0047B90C 2B38         */ IL_0038: br.s      IL_0072

			/* 0x0047B90E 02           */ IL_003A: ldarg.0
			/* 0x0047B90F 2830D50106   */ IL_003B: call      instance int32 _omuaGIHkpB8HgJH84kunzdF5Q8b._GmpWUy9gO61zI05x0MXZNizw70H::_i9DigvkWX2SB3p3DrJmaYrmrUHt()
			/* 0x0047B914 06           */ IL_0040: ldloc.0
			/* 0x0047B915 3308         */ IL_0041: bne.un.s  IL_004B

			/* 0x0047B917 20DD238B34   */ IL_0043: ldc.i4    881533917
			/* 0x0047B91C 25           */ IL_0048: dup
			/* 0x0047B91D 2B06         */ IL_0049: br.s      IL_0051

			/* 0x0047B91F 20D7CB1017   */ IL_004B: ldc.i4    386976727
			/* 0x0047B924 25           */ IL_0050: dup

			/* 0x0047B925 26           */ IL_0051: pop
			/* 0x0047B926 07           */ IL_0052: ldloc.1
			/* 0x0047B927 20B4565C40   */ IL_0053: ldc.i4    1079793332
			/* 0x0047B92C 5A           */ IL_0058: mul
			/* 0x0047B92D 61           */ IL_0059: xor
			/* 0x0047B92E 2BBD         */ IL_005A: br.s      IL_0019

			/* 0x0047B930 02           */ IL_005C: ldarg.0
			/* 0x0047B931 06           */ IL_005D: ldloc.0
			/* 0x0047B932 2831D50106   */ IL_005E: call      instance void _omuaGIHkpB8HgJH84kunzdF5Q8b._GmpWUy9gO61zI05x0MXZNizw70H::_gH3Za3IkwrlXsCfFJ39D30O9ZWL(int32)
			/* 0x0047B937 07           */ IL_0063: ldloc.1
			/* 0x0047B938 204B101AD1   */ IL_0064: ldc.i4    -786821045
			/* 0x0047B93D 5A           */ IL_0069: mul
			/* 0x0047B93E 206BBA3D05   */ IL_006A: ldc.i4    87931499
			/* 0x0047B943 61           */ IL_006F: xor
			/* 0x0047B944 2BA7         */ IL_0070: br.s      IL_0019
		// end loop

		/* 0x0047B946 2A           */ IL_0072: ret
	} // end of method _GmpWUy9gO61zI05x0MXZNizw70H::_jpXhRjjjc80FUFutwWTZWcZsPyc
```
result in a decompile exception in dnspy after unpacking

```C#
private int _JsyVKTz4egDrDK4nIzziWABIPAe
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    get
    {
        return this._OQoQ9XbznT8Iu2jioNCdczfKRBJ;
    }
    set
    {
        /*
An exception occurred when decompiling this method (0601D531)

ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Void _omuaGIHkpB8HgJH84kunzdF5Q8b._GmpWUy9gO61zI05x0MXZNizw70H::_gH3Za3IkwrlXsCfFJ39D30O9ZWL(System.Int32)
---> System.Exception: Inconsistent stack size at IL_11
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.StackAnalysis(MethodDef methodDef) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstBuilder.cs:line 443
   at ICSharpCode.Decompiler.ILAst.ILAstBuilder.Build(MethodDef methodDef, Boolean optimize, DecompilerContext context) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\ILAstBuilder.cs:line 269
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MethodDebugInfoBuilder& builder) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 112
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 88
   --- End of inner exception stack trace ---
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, AutoPropertyProvider autoPropertyProvider, IEnumerable`1 parameters, Boolean valueParameterIsKeyword, StringBuilder sb, MethodDebugInfoBuilder& stmtsBuilder) in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:line 92
   at ICSharpCode.Decompiler.Ast.AstBuilder.<>c__DisplayClass89_1.<AddMethodBody>b__0() in C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\Ast\AstBuilder.cs:line 1531
*/;
    }
}
```
Happy to do what I can to help fix this

**Comment by cawk** [comment]
is this the file from RTN if not can you send it me, if you dont want to post it public email it me here
cawkre@gmail.com

**Comment by fl380** [comment]
it's the same file
